export const ACTIVITY_LIST = 'ACTIVITY_LIST'
export const ACTIVITY_ADD = 'ACTIVITY_ADD'
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE'
export const ACTIVITY_REMOVE = 'ACTIVITY_REMOVE'

export default {
  ACTIVITY_LIST,
  ACTIVITY_ADD,
  ACTIVITY_UPDATE,
  ACTIVITY_REMOVE,
}